import Head from 'next/head';
import { Container, Select, Button, Text, Divider } from '@mantine/core';
import { CheckItem } from '../types/items';
import Router from 'next/router';
import Image from 'next/image';
import useLocalStorageState from 'use-local-storage-state';
import styles from '../styles/check.module.css';

const createMessage = (checkList: CheckItem[]) => {
  return `
  新しい注文がありました：
${checkList.map((order) => `${order.title}: ${order.count}`).join('\n')}
  `;
};
const handler = (path: string) => {
  Router.push(path);
};

const data = Array(10)
  .fill(0)
  .map((_, index) => `${index + 1}`);

function CheckList() {
  const [checkList, setCheckList] =
    useLocalStorageState<CheckItem[]>('checkList');

  const handleDelete = (index: number) => {
    const updatedCheckList = [...(checkList ?? [])];
    updatedCheckList.splice(index, 1);
    setCheckList(updatedCheckList);
  };

  const onChange = (index: number, count: string | null) => {
    if (count !== null) {
      setCheckList((checkList) => {
        const updatedCheckList = [...(checkList ?? [])];
        updatedCheckList[index] = {
          ...updatedCheckList[index],
          count: Number(count),
        };
        return updatedCheckList;
      });
    }
  };
  const calculatedTotalCount = checkList?.reduce(
    (total, item) => total + item.count,
    0,
  );
  const calculatedTotalPrice = checkList?.reduce(
    (total, item) => total + item.price * item.count,
    0,
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="title" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image
        src="/tacos-bg.jpeg"
        alt=""
        width={1500}
        height={500}
        style={{
          minWidth: '100%',
          marginTop: '-150px',
          marginBottom: '-100px',
          objectFit: 'cover',
          objectPosition: 'center bottom',
          clipPath: 'inset(30% 0 25% 0)',
        }}
      />
      <Container style={{ width: '100%', height: '100px', marginTop: '15px' }}>
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            fontSize: 35,
            fontWeight: 600,
            textAlign: 'center',
          }}
        >
          Carol Tacos 注文カート
          <Button
            radius="xl"
            size="sm"
            color="gray"
            style={{ marginLeft: '30px' }}
            onClick={() => handler('/order')}
          >
            <div style={{ margin: '10px' }}>注文ページに戻る</div>
          </Button>
        </div>
      </Container>
      <div
        style={{
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <table style={{ borderCollapse: 'collapse' }} cellSpacing={100}>
          <tbody>
            {checkList
              ?.slice()
              .reverse()
              .map((row, index) => (
                <div key={index} style={{ padding: '20px' }}>
                  <tr style={{ position: 'relative', textAlign: 'center' }}>
                    <td>
                      <Image
                        src={row.image}
                        alt="title image"
                        width={140}
                        height={95}
                      />
                    </td>
                    <td style={{ width: '250px', padding: '20px' }}>
                      <Text>{row.title}</Text>
                    </td>
                    <td style={{ width: '100px', padding: '20px' }}>
                      ¥{row.price}
                    </td>
                    <td style={{ width: '150px', padding: '20px' }}>
                      <Select
                        style={{ width: '60px' }}
                        defaultValue={String(row.count)}
                        data={data}
                        placeholder="0"
                        maxDropdownHeight={100}
                        size="xs"
                        onChange={(count) => onChange(index, count)}
                      />
                    </td>
                    <td>
                      <a
                        onClick={() => handleDelete(index)}
                        className={styles.deleteLink}
                      >
                        削除
                      </a>
                    </td>
                  </tr>
                </div>
              ))}
          </tbody>
        </table>
      </div>
      <Divider my="sm" style={{ width: '50%', margin: 'auto' }} />
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          width: '50%',
          margin: 'auto',
        }}
      >
        <p style={{ textAlign: 'right', margin: '20px', flex: '1' }}>合計</p>
        <p style={{ marginLeft: '50px' }}>¥{calculatedTotalPrice}</p>
        <p style={{ marginLeft: '60px', marginRight: '50px' }}>
          {calculatedTotalCount}点
        </p>
        <Button
          radius="xl"
          size="sm"
          color="dark"
          onClick={() => {
            if (checkList && checkList.length > 0) {
              handler('/thanks');
              setCheckList([]);
              fetch('/api/slack', {
                method: 'POST',
                body: createMessage(checkList),
              });
            }
          }}
          disabled={checkList && checkList.length === 0}
        >
          <div style={{ margin: '10px' }}>確定</div>
        </Button>
      </div>
    </>
  );
}

export default function CheckPage() {
  return (
    <div>
      <CheckList />
    </div>
  );
}
